const actionKeys = {
  actionsPendingAdd: 'REQUEST_PENDING_ADD',
  actionsPendingRemove: 'REQUEST_PENDING_REMOVE',
  apiError: 'API_ERROR',
  criteriaTestReadKey: 'CRITERIA_TEST_READ_KEY',
  criteriaTestReadRequestKey: 'CRITERIA_TEST_READ_REQUEST_KEY',
  criteriaTestClearKey: 'CRITERIA_TEST_CLEAR_KEY',
  duplicatesReadRequestKey: 'DUPLICATES_READ_REQUEST_KEY',
  duplicatesReadRequestKey: 'DUPLICATES_READ_REQUEST_KEY',
  importDataRequestKey: 'IMPORT_DATA_REQUEST_KEY',
  ruleCreateKey: 'RULE_CREATE_KEY',
  ruleCreateRequestKey: 'RULE_CREATE_REQUEST_KEY',
  ruleDeleteRequestKey: 'RULE_DELETE_REQUEST_KEY',
  rulesReadKey: 'RULES_READ_KEY',
  ruleReadByIdRequestKey: 'RULE_READ_BY_ID_REQUEST_KEY',
  rulesReadRequestKey: 'RULES_READ_REQUEST_KEY',
  ruleUpdateRequestKey: 'RULE_UPDATE_REQUEST_KEY',
  ruleUpdateKey: 'RULE_UPDATE_KEY',
  ruleNewKey: 'RULE_NEW_KEY',
  ruleTmpAddKey: 'RULETMP_ADD_KEY',
  ruleTmpRemoveKey: 'RULETMP_REMOVE_KEY',
  ruleTmpUpdateKep: 'RULETMP_UPDATE_KEY',
  ruleIdShowSetKey: 'ROW_ID_SHOW_SET_KEY',
  rowIdShoreClearKey: 'ROW_ID_SHOW_CLEAR_KEY',
  currentViewNameSet: 'CURRENT_VIEW_NAME_SET',
  currentViewNameClear: 'CURRENT_VIEW_NAME_CLEAR',
  viewReadKey: 'VIEW_READ_KEY',
  viewReadRequestKey: 'VIEW_READ_REQUEST_KEY',
  requestPending: 'REQUEST_PENDING',
  requestSuccess: 'REQUEST_SUCCESS',
  requestFailure: 'REQUEST_FAILURE',
}

export default actionKeys