const actionKeys = {
  actionsPendingAdd: 'REQUEST_PENDING_ADD',
  actionsPendingRemove: 'REQUEST_PENDING_REMOVE',
  apiError: 'API_ERROR',
  criteriaTestReadKey: 'CRITERIA_TEST_READ_KEY',
  criteriaTestReadRequestKey: 'CRITERIA_TEST_READ_REQUEST_KEY',
  criteriaTestClearKey: 'CRITERIA_TEST_CLEAR_KEY',
  currentViewNameSet: 'CURRENT_VIEW_NAME_SET',
  currentViewNameClear: 'CURRENT_VIEW_NAME_CLEAR',
  duplicatesReadKey: 'DUPLICATES_READ_KEY',
  duplicatesReadRequestKey: 'DUPLICATES_READ_REQUEST_KEY',
  importDataRequestKey: 'IMPORT_DATA_REQUEST_KEY',
  requestPending: 'REQUEST_PENDING',
  requestSuccess: 'REQUEST_SUCCESS',
  requestFailure: 'REQUEST_FAILURE',
  ruleCreateKey: 'RULE_CREATE_KEY',
  ruleCreateRequestKey: 'RULE_CREATE_REQUEST_KEY',
  ruleDeleteRequestKey: 'RULE_DELETE_REQUEST_KEY',
  rowIdShowSetKey: 'ROW_ID_SHOW_SET_KEY',
  rowIdShowClearKey: 'ROW_ID_SHOW_CLEAR_KEY',
  ruleNewKey: 'RULE_NEW_KEY',
  rulesReadKey: 'RULES_READ_KEY',
  ruleReadByIdRequestKey: 'RULE_READ_BY_ID_REQUEST_KEY',
  rulesReadRequestKey: 'RULES_READ_REQUEST_KEY',
  ruleUpdateRequestKey: 'RULE_UPDATE_REQUEST_KEY',
  ruleUpdateKey: 'RULE_UPDATE_KEY',
  ruleTmpAddKey: 'RULETMP_ADD_KEY',
  ruleTmpCriterionAddKey: 'RULETMP_CRITERION_ADD_KEY',
  ruleTmpCriterionDeleteKey: 'RULETMP_CRITERION_DELETE_KEY',
  ruleTmpCriterionUpdateAction: 'RULETMP_CRITERION_UPDATE_KEY',

  ruleTmpActionAddKey: 'RULETMP_ACTION_ADD_KEY',
  ruleTmpActionDeleteKey: 'RULETMP_ACTION_DELETE_KEY',
  ruleTmpActionUpdateAction: 'RULETMP_ACTION_UPDATE_KEY',

  ruleTmpRemoveKey: 'RULETMP_REMOVE_KEY',
  ruleTmpUpdateKey: 'RULETMP_UPDATE_KEY',
  toastSetKey: 'TOAST_SET_KEY',
  toastClearKey: 'TOAST_CLEAR_KEY',
  viewReadKey: 'VIEW_READ_KEY',
  viewReadRequestKey: 'VIEW_READ_REQUEST_KEY',
}

export default actionKeys